# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c31f3a760b6303fa86ec2ac307792c5a910c4a1ae7409a32dd038ce0fe86486f8d0ac6a6287b8ced1cd6a7510bcb9814c7f28ebb215a2ad6e9f5243a4473fd66

test:
  secret_key_base: 2bc01f1df38d9dc315dd6a19ce84decb17ca84c44b6b89287f0921aa3f0a89c2abb271fd13ad293423231d9244a8b9b6ab7f46b635850f140f3d69f2ddc98977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
